require('dotenv').config();
const neo4j = require('neo4j-driver');

const driver = neo4j.driver(
  process.env.NEO4J_URI,
  neo4j.auth.basic(process.env.NEO4J_USER, process.env.NEO4J_PASSWORD)
);

const movies = [
  { title: 'The Godfather', year: 1972, rating: 9.2 },
  { title: 'The Godfather Part II', year: 1974, rating: 9.0 },
  { title: 'The Shawshank Redemption', year: 1994, rating: 9.3 },
  { title: 'Pulp Fiction', year: 1994, rating: 8.9 },
  { title: 'The Dark Knight', year: 2008, rating: 9.0 },
  { title: 'Forrest Gump', year: 1994, rating: 8.8 },
  { title: 'Inception', year: 2010, rating: 8.8 },
  { title: 'The Matrix', year: 1999, rating: 8.7 },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, rating: 8.8 },
  { title: 'The Lord of the Rings: The Two Towers', year: 2002, rating: 8.7 },
  { title: 'The Lord of the Rings: The Return of the King', year: 2003, rating: 9.0 },
  { title: 'Interstellar', year: 2014, rating: 8.6 },
  { title: 'The Departed', year: 2006, rating: 8.5 },
  { title: 'The Wolf of Wall Street', year: 2013, rating: 8.2 },
  { title: 'Django Unchained', year: 2012, rating: 8.4 },
  { title: 'Inglourious Basterds', year: 2009, rating: 8.3 },
  { title: 'The Social Network', year: 2010, rating: 7.7 },
  { title: 'The Avengers', year: 2012, rating: 8.0 },
  { title: 'Black Panther', year: 2018, rating: 7.3 },
  { title: 'Joker', year: 2019, rating: 8.4 },
  { title: 'Parasite', year: 2019, rating: 8.5 },
  { title: 'Once Upon a Time in Hollywood', year: 2019, rating: 7.6 },
  { title: 'John Wick', year: 2014, rating: 7.4 },
  { title: 'John Wick: Chapter 2', year: 2017, rating: 7.5 },
  { title: 'John Wick: Chapter 3 - Parabellum', year: 2019, rating: 7.4 },
  { title: 'Casino Royale', year: 2006, rating: 8.0 },
  { title: 'Skyfall', year: 2012, rating: 7.8 },
  { title: 'Dune', year: 2021, rating: 8.0 },
  { title: 'Dune: Part Two', year: 2024, rating: 8.3 },
  { title: 'Barbie', year: 2023, rating: 7.0 },
  { title: 'Oppenheimer', year: 2023, rating: 8.4 },
  { title: 'La La Land', year: 2016, rating: 8.0 },
  { title: 'Get Out', year: 2017, rating: 7.8 },
  { title: 'The Revenant', year: 2015, rating: 8.0 },
  { title: 'The Big Short', year: 2015, rating: 7.8 },
  { title: 'Mad Max: Fury Road', year: 2015, rating: 8.1 },
];

const people = [
  { name: 'Marlon Brando', born: 1924 },
  { name: 'Al Pacino', born: 1940 },
  { name: 'Robert De Niro', born: 1943 },
  { name: 'Morgan Freeman', born: 1937 },
  { name: 'Tim Robbins', born: 1958 },
  { name: 'John Travolta', born: 1954 },
  { name: 'Samuel L. Jackson', born: 1948 },
  { name: 'Uma Thurman', born: 1970 },
  { name: 'Christian Bale', born: 1974 },
  { name: 'Heath Ledger', born: 1979 },
  { name: 'Michael Caine', born: 1933 },
  { name: 'Tom Hanks', born: 1956 },
  { name: 'Leonardo DiCaprio', born: 1974 },
  { name: 'Joseph Gordon-Levitt', born: 1981 },
  { name: 'Tom Hardy', born: 1977 },
  { name: 'Keanu Reeves', born: 1964 },
  { name: 'Laurence Fishburne', born: 1961 },
  { name: 'Carrie-Anne Moss', born: 1967 },
  { name: 'Elijah Wood', born: 1981 },
  { name: 'Ian McKellen', born: 1939 },
  { name: 'Viggo Mortensen', born: 1958 },
  { name: 'Matthew McConaughey', born: 1969 },
  { name: 'Anne Hathaway', born: 1982 },
  { name: 'Jack Nicholson', born: 1937 },
  { name: 'Matt Damon', born: 1970 },
  { name: 'Jonah Hill', born: 1983 },
  { name: 'Margot Robbie', born: 1990 },
  { name: 'Brad Pitt', born: 1963 },
  { name: 'Christoph Waltz', born: 1956 },
  { name: 'Jamie Foxx', born: 1967 },
  { name: 'Jesse Eisenberg', born: 1983 },
  { name: 'Robert Downey Jr.', born: 1965 },
  { name: 'Chris Evans', born: 1981 },
  { name: 'Scarlett Johansson', born: 1984 },
  { name: 'Chadwick Boseman', born: 1976 },
  { name: 'Joaquin Phoenix', born: 1974 },
  { name: 'Song Kang-ho', born: 1967 },
  { name: 'Daniel Craig', born: 1968 },
  { name: 'Ryan Gosling', born: 1980 },
  { name: 'Emma Stone', born: 1988 },
  { name: 'Daniel Kaluuya', born: 1989 },
  { name: 'Timothée Chalamet', born: 1995 },
  { name: 'Zendaya', born: 1996 },
  { name: 'Cillian Murphy', born: 1976 },
  { name: 'Francis Ford Coppola', born: 1939 },
  { name: 'Frank Darabont', born: 1959 },
  { name: 'Quentin Tarantino', born: 1963 },
  { name: 'Christopher Nolan', born: 1970 },
  { name: 'Robert Zemeckis', born: 1951 },
  { name: 'Lana Wachowski', born: 1965 },
  { name: 'Peter Jackson', born: 1961 },
  { name: 'Martin Scorsese', born: 1942 },
  { name: 'David Fincher', born: 1962 },
  { name: 'Joss Whedon', born: 1964 },
  { name: 'Ryan Coogler', born: 1986 },
  { name: 'Todd Phillips', born: 1970 },
  { name: 'Bong Joon-ho', born: 1969 },
  { name: 'George Miller', born: 1945 },
  { name: 'Damien Chazelle', born: 1985 },
  { name: 'Jordan Peele', born: 1979 },
  { name: 'Greta Gerwig', born: 1983 },
  { name: 'Denis Villeneuve', born: 1967 },
];

const genres = ['Action', 'Adventure', 'Biography', 'Comedy', 'Crime', 'Drama', 'Fantasy', 'History', 'Horror', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'];

const actedIn = [
  { person: 'Marlon Brando', movie: 'The Godfather' },
  { person: 'Al Pacino', movie: 'The Godfather' },
  { person: 'Robert De Niro', movie: 'The Godfather Part II' },
  { person: 'Al Pacino', movie: 'The Godfather Part II' },
  { person: 'Morgan Freeman', movie: 'The Shawshank Redemption' },
  { person: 'Tim Robbins', movie: 'The Shawshank Redemption' },
  { person: 'John Travolta', movie: 'Pulp Fiction' },
  { person: 'Samuel L. Jackson', movie: 'Pulp Fiction' },
  { person: 'Uma Thurman', movie: 'Pulp Fiction' },
  { person: 'Christian Bale', movie: 'The Dark Knight' },
  { person: 'Heath Ledger', movie: 'The Dark Knight' },
  { person: 'Morgan Freeman', movie: 'The Dark Knight' },
  { person: 'Michael Caine', movie: 'The Dark Knight' },
  { person: 'Tom Hanks', movie: 'Forrest Gump' },
  { person: 'Leonardo DiCaprio', movie: 'Inception' },
  { person: 'Joseph Gordon-Levitt', movie: 'Inception' },
  { person: 'Tom Hardy', movie: 'Inception' },
  { person: 'Michael Caine', movie: 'Inception' },
  { person: 'Keanu Reeves', movie: 'The Matrix' },
  { person: 'Laurence Fishburne', movie: 'The Matrix' },
  { person: 'Carrie-Anne Moss', movie: 'The Matrix' },
  { person: 'Elijah Wood', movie: 'The Lord of the Rings: The Fellowship of the Ring' },
  { person: 'Ian McKellen', movie: 'The Lord of the Rings: The Fellowship of the Ring' },
  { person: 'Viggo Mortensen', movie: 'The Lord of the Rings: The Fellowship of the Ring' },
  { person: 'Elijah Wood', movie: 'The Lord of the Rings: The Two Towers' },
  { person: 'Ian McKellen', movie: 'The Lord of the Rings: The Two Towers' },
  { person: 'Elijah Wood', movie: 'The Lord of the Rings: The Return of the King' },
  { person: 'Ian McKellen', movie: 'The Lord of the Rings: The Return of the King' },
  { person: 'Matthew McConaughey', movie: 'Interstellar' },
  { person: 'Anne Hathaway', movie: 'Interstellar' },
  { person: 'Michael Caine', movie: 'Interstellar' },
  { person: 'Leonardo DiCaprio', movie: 'The Departed' },
  { person: 'Matt Damon', movie: 'The Departed' },
  { person: 'Jack Nicholson', movie: 'The Departed' },
  { person: 'Leonardo DiCaprio', movie: 'The Wolf of Wall Street' },
  { person: 'Jonah Hill', movie: 'The Wolf of Wall Street' },
  { person: 'Margot Robbie', movie: 'The Wolf of Wall Street' },
  { person: 'Jamie Foxx', movie: 'Django Unchained' },
  { person: 'Christoph Waltz', movie: 'Django Unchained' },
  { person: 'Leonardo DiCaprio', movie: 'Django Unchained' },
  { person: 'Brad Pitt', movie: 'Inglourious Basterds' },
  { person: 'Christoph Waltz', movie: 'Inglourious Basterds' },
  { person: 'Jesse Eisenberg', movie: 'The Social Network' },
  { person: 'Robert Downey Jr.', movie: 'The Avengers' },
  { person: 'Chris Evans', movie: 'The Avengers' },
  { person: 'Scarlett Johansson', movie: 'The Avengers' },
  { person: 'Chadwick Boseman', movie: 'Black Panther' },
  { person: 'Joaquin Phoenix', movie: 'Joker' },
  { person: 'Robert De Niro', movie: 'Joker' },
  { person: 'Song Kang-ho', movie: 'Parasite' },
  { person: 'Leonardo DiCaprio', movie: 'Once Upon a Time in Hollywood' },
  { person: 'Brad Pitt', movie: 'Once Upon a Time in Hollywood' },
  { person: 'Margot Robbie', movie: 'Once Upon a Time in Hollywood' },
  { person: 'Keanu Reeves', movie: 'John Wick' },
  { person: 'Keanu Reeves', movie: 'John Wick: Chapter 2' },
  { person: 'Keanu Reeves', movie: 'John Wick: Chapter 3 - Parabellum' },
  { person: 'Daniel Craig', movie: 'Casino Royale' },
  { person: 'Daniel Craig', movie: 'Skyfall' },
  { person: 'Timothée Chalamet', movie: 'Dune' },
  { person: 'Zendaya', movie: 'Dune' },
  { person: 'Timothée Chalamet', movie: 'Dune: Part Two' },
  { person: 'Zendaya', movie: 'Dune: Part Two' },
  { person: 'Margot Robbie', movie: 'Barbie' },
  { person: 'Ryan Gosling', movie: 'Barbie' },
  { person: 'Cillian Murphy', movie: 'Oppenheimer' },
  { person: 'Robert Downey Jr.', movie: 'Oppenheimer' },
  { person: 'Matt Damon', movie: 'Oppenheimer' },
  { person: 'Ryan Gosling', movie: 'La La Land' },
  { person: 'Emma Stone', movie: 'La La Land' },
  { person: 'Daniel Kaluuya', movie: 'Get Out' },
  { person: 'Leonardo DiCaprio', movie: 'The Revenant' },
  { person: 'Tom Hardy', movie: 'The Revenant' },
  { person: 'Christian Bale', movie: 'The Big Short' },
  { person: 'Ryan Gosling', movie: 'The Big Short' },
  { person: 'Tom Hardy', movie: 'Mad Max: Fury Road' },
];

const directed = [
  { person: 'Francis Ford Coppola', movie: 'The Godfather' },
  { person: 'Francis Ford Coppola', movie: 'The Godfather Part II' },
  { person: 'Frank Darabont', movie: 'The Shawshank Redemption' },
  { person: 'Quentin Tarantino', movie: 'Pulp Fiction' },
  { person: 'Quentin Tarantino', movie: 'Django Unchained' },
  { person: 'Quentin Tarantino', movie: 'Inglourious Basterds' },
  { person: 'Quentin Tarantino', movie: 'Once Upon a Time in Hollywood' },
  { person: 'Christopher Nolan', movie: 'The Dark Knight' },
  { person: 'Christopher Nolan', movie: 'Inception' },
  { person: 'Christopher Nolan', movie: 'Interstellar' },
  { person: 'Christopher Nolan', movie: 'Oppenheimer' },
  { person: 'Robert Zemeckis', movie: 'Forrest Gump' },
  { person: 'Lana Wachowski', movie: 'The Matrix' },
  { person: 'Peter Jackson', movie: 'The Lord of the Rings: The Fellowship of the Ring' },
  { person: 'Peter Jackson', movie: 'The Lord of the Rings: The Two Towers' },
  { person: 'Peter Jackson', movie: 'The Lord of the Rings: The Return of the King' },
  { person: 'Martin Scorsese', movie: 'The Departed' },
  { person: 'Martin Scorsese', movie: 'The Wolf of Wall Street' },
  { person: 'David Fincher', movie: 'The Social Network' },
  { person: 'Joss Whedon', movie: 'The Avengers' },
  { person: 'Ryan Coogler', movie: 'Black Panther' },
  { person: 'Todd Phillips', movie: 'Joker' },
  { person: 'Bong Joon-ho', movie: 'Parasite' },
  { person: 'George Miller', movie: 'Mad Max: Fury Road' },
  { person: 'Damien Chazelle', movie: 'La La Land' },
  { person: 'Jordan Peele', movie: 'Get Out' },
  { person: 'Greta Gerwig', movie: 'Barbie' },
  { person: 'Denis Villeneuve', movie: 'Dune' },
  { person: 'Denis Villeneuve', movie: 'Dune: Part Two' },
];

const movieGenres = [
  { movie: 'The Godfather', genre: 'Crime' }, { movie: 'The Godfather', genre: 'Drama' },
  { movie: 'The Godfather Part II', genre: 'Crime' }, { movie: 'The Godfather Part II', genre: 'Drama' },
  { movie: 'The Shawshank Redemption', genre: 'Drama' },
  { movie: 'Pulp Fiction', genre: 'Crime' }, { movie: 'Pulp Fiction', genre: 'Drama' },
  { movie: 'The Dark Knight', genre: 'Action' }, { movie: 'The Dark Knight', genre: 'Crime' }, { movie: 'The Dark Knight', genre: 'Drama' },
  { movie: 'Forrest Gump', genre: 'Drama' }, { movie: 'Forrest Gump', genre: 'Romance' },
  { movie: 'Inception', genre: 'Action' }, { movie: 'Inception', genre: 'Sci-Fi' }, { movie: 'Inception', genre: 'Thriller' },
  { movie: 'The Matrix', genre: 'Action' }, { movie: 'The Matrix', genre: 'Sci-Fi' },
  { movie: 'The Lord of the Rings: The Fellowship of the Ring', genre: 'Adventure' }, { movie: 'The Lord of the Rings: The Fellowship of the Ring', genre: 'Fantasy' },
  { movie: 'The Lord of the Rings: The Two Towers', genre: 'Adventure' }, { movie: 'The Lord of the Rings: The Two Towers', genre: 'Fantasy' },
  { movie: 'The Lord of the Rings: The Return of the King', genre: 'Adventure' }, { movie: 'The Lord of the Rings: The Return of the King', genre: 'Fantasy' },
  { movie: 'Interstellar', genre: 'Adventure' }, { movie: 'Interstellar', genre: 'Sci-Fi' }, { movie: 'Interstellar', genre: 'Drama' },
  { movie: 'The Departed', genre: 'Crime' }, { movie: 'The Departed', genre: 'Thriller' },
  { movie: 'The Wolf of Wall Street', genre: 'Biography' }, { movie: 'The Wolf of Wall Street', genre: 'Comedy' }, { movie: 'The Wolf of Wall Street', genre: 'Crime' },
  { movie: 'Django Unchained', genre: 'Drama' }, { movie: 'Django Unchained', genre: 'Western' },
  { movie: 'Inglourious Basterds', genre: 'Drama' }, { movie: 'Inglourious Basterds', genre: 'War' },
  { movie: 'The Social Network', genre: 'Biography' }, { movie: 'The Social Network', genre: 'Drama' },
  { movie: 'The Avengers', genre: 'Action' }, { movie: 'The Avengers', genre: 'Sci-Fi' },
  { movie: 'Black Panther', genre: 'Action' }, { movie: 'Black Panther', genre: 'Sci-Fi' },
  { movie: 'Joker', genre: 'Crime' }, { movie: 'Joker', genre: 'Drama' }, { movie: 'Joker', genre: 'Thriller' },
  { movie: 'Parasite', genre: 'Comedy' }, { movie: 'Parasite', genre: 'Drama' }, { movie: 'Parasite', genre: 'Thriller' },
  { movie: 'Once Upon a Time in Hollywood', genre: 'Comedy' }, { movie: 'Once Upon a Time in Hollywood', genre: 'Drama' },
  { movie: 'John Wick', genre: 'Action' }, { movie: 'John Wick', genre: 'Crime' }, { movie: 'John Wick', genre: 'Thriller' },
  { movie: 'John Wick: Chapter 2', genre: 'Action' }, { movie: 'John Wick: Chapter 2', genre: 'Thriller' },
  { movie: 'John Wick: Chapter 3 - Parabellum', genre: 'Action' }, { movie: 'John Wick: Chapter 3 - Parabellum', genre: 'Thriller' },
  { movie: 'Casino Royale', genre: 'Action' }, { movie: 'Casino Royale', genre: 'Thriller' },
  { movie: 'Skyfall', genre: 'Action' }, { movie: 'Skyfall', genre: 'Thriller' },
  { movie: 'Dune', genre: 'Action' }, { movie: 'Dune', genre: 'Adventure' }, { movie: 'Dune', genre: 'Sci-Fi' },
  { movie: 'Dune: Part Two', genre: 'Action' }, { movie: 'Dune: Part Two', genre: 'Adventure' }, { movie: 'Dune: Part Two', genre: 'Sci-Fi' },
  { movie: 'Barbie', genre: 'Comedy' }, { movie: 'Barbie', genre: 'Fantasy' },
  { movie: 'Oppenheimer', genre: 'Biography' }, { movie: 'Oppenheimer', genre: 'Drama' }, { movie: 'Oppenheimer', genre: 'History' },
  { movie: 'La La Land', genre: 'Comedy' }, { movie: 'La La Land', genre: 'Drama' }, { movie: 'La La Land', genre: 'Romance' },
  { movie: 'Get Out', genre: 'Horror' }, { movie: 'Get Out', genre: 'Mystery' }, { movie: 'Get Out', genre: 'Thriller' },
  { movie: 'The Revenant', genre: 'Adventure' }, { movie: 'The Revenant', genre: 'Drama' }, { movie: 'The Revenant', genre: 'Western' },
  { movie: 'The Big Short', genre: 'Biography' }, { movie: 'The Big Short', genre: 'Comedy' }, { movie: 'The Big Short', genre: 'Drama' },
  { movie: 'Mad Max: Fury Road', genre: 'Action' }, { movie: 'Mad Max: Fury Road', genre: 'Adventure' }, { movie: 'Mad Max: Fury Road', genre: 'Sci-Fi' },
];

async function seed() {
  const session = driver.session();
  try {
    console.log('Clearing old data...');
    await session.run('MATCH (n) DETACH DELETE n');

    console.log('Creating movies...');
    for (const m of movies) await session.run('CREATE (:Movie {title: $title, year: $year, rating: $rating})', m);

    console.log('Creating people...');
    for (const p of people) await session.run('CREATE (:Person {name: $name, born: $born})', p);

    console.log('Creating genres...');
    for (const g of genres) await session.run('CREATE (:Genre {name: $name})', { name: g });

    console.log('Creating ACTED_IN relationships...');
    for (const r of actedIn) await session.run(`MATCH (p:Person {name: $person}), (m:Movie {title: $movie}) CREATE (p)-[:ACTED_IN]->(m)`, r);

    console.log('Creating DIRECTED relationships...');
    for (const r of directed) await session.run(`MATCH (p:Person {name: $person}), (m:Movie {title: $movie}) CREATE (p)-[:DIRECTED]->(m)`, r);

    console.log('Creating IN_GENRE relationships...');
    for (const r of movieGenres) await session.run(`MATCH (m:Movie {title: $movie}), (g:Genre {name: $genre}) CREATE (m)-[:IN_GENRE]->(g)`, r);

    console.log(`Done! Seeded ${movies.length} movies, ${people.length} people, ${genres.length} genres.`);
  } catch (err) {
    console.error('Seeding failed:', err);
  } finally {
    await session.close();
    await driver.close();
  }
}

seed();